# Generated by Django 3.2.13 on 2022-11-20 13:27

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, upload_to=community.models.user_image_path),
        ),
    ]
